language: ru

pipeline:
- name: WhitespaceTokenizer
- name: RegexFeaturizer
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
  analyzer: "char_wb"
  min_ngram: 2
  max_ngram: 3

- name: "LanguageModelFeaturizer"
  model_name: "bert"
  model_weights: "bert-base-multilingual-cased"
  cache_dir: null

- name: DIETClassifier
  epochs: 50
  transformer_size: 64
  number_of_transformer_layers: 2
  use_masked_language_model: false
  batch_strategy: "balanced"
  hidden_layers_sizes:
    text: [64, 32]

- name: EntitySynonymMapper
- name: ResponseSelector
  epochs: 50

policies:
- name: MemoizationPolicy
  max_history: 5
- name: RulePolicy
- name: TEDPolicy
  max_history: 5
  epochs: 50
  constrain_similarities: true